
"@context":

ontologies:

  - id: go
    preferredPrefix: GO
    title: Gene Ontology
    description: 
    uri: http://purl.obolibrary.org/obo/go.owl
    base_uri: 
      - http://purl.obolibrary.org/obo/go/GO_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    oboSlims: true
    ontology_purl: http://purl.obolibrary.org/obo/go.owl


  - id: cl
    preferredPrefix: CL
    title: Cell Ontology
    description: 
    uri: http://purl.obolibrary.org/obo/cl.owl
    base_uri: 
      - http://purl.obolibrary.org/obo/cl/CL_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    oboSlims: true
    ontology_purl: http://purl.obolibrary.org/obo/cl.owl


  - id: pato
    preferredPrefix: PATO
    title: Phenotypic quality
    description: 
    uri: http://purl.obolibrary.org/obo/pato.owl
    base_uri: 
      - http://purl.obolibrary.org/obo/pato/PATO_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    oboSlims: true
    ontology_purl: http://purl.obolibrary.org/obo/pato.owl


  - id: doid
    preferredPrefix: DOID
    title: Human Disease Ontology
    description: 
    uri: http://purl.obolibrary.org/obo/doid.owl
    base_uri: 
      - http://purl.obolibrary.org/obo/doid/DOID_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    oboSlims: true
    ontology_purl: http://purl.obolibrary.org/obo/doid.owl


  - id: hp
    preferredPrefix: HP
    title: human phenotype ontology
    description: 
    uri: http://purl.obolibrary.org/obo/hp.owl
    base_uri: 
      - http://purl.obolibrary.org/obo/hp/HP_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    oboSlims: true
    ontology_purl: http://purl.obolibrary.org/obo/hp.owl


  - id: fma
    preferredPrefix: FMA
    title: Foundational Model of Anatomy (subset)
    description: 
    uri: http://purl.obolibrary.org/obo/fma.owl
    base_uri: 
      - http://purl.obolibrary.org/obo/fma/FMA_
    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasNarrowSynonym
      - http://www.geneontology.org/formats/oboInOwl#hasExactSynonym
    definition_property:
      - http://purl.obolibrary.org/obo/IAO_0000115
    hierarchical_property:
      - http://purl.obolibrary.org/obo/BFO_0000050
    oboSlims: true
    ontology_purl: http://purl.obolibrary.org/obo/fma.owl


